# Generated by Django 6.1.1 on 2026-09-04 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('icone', models.CharField(default='📚', max_length=10)),
            ],
        ),
    ]
