# Generated by Django 6.1.1 on 2026-09-04 04:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudos', '0002_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='area',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='estudos.area'),
            preserve_default=False,
        ),
    ]
