# Generated by Django 6.1.1 on 2026-09-04 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudos', '0003_categoria_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AddField(
            model_name='categoria',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AddField(
            model_name='conteudo',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
