# Generated by Django 6.1.1 on 2026-09-04 04:54

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estudos', '0004_area_slug_categoria_slug_conteudo_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conteudo',
            name='conteudo',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Conteúdo'),
        ),
    ]
